"use client";

import { useEffect, useState } from "react";
import { Calendar, Check, FileStack, HardDrive, Mail, PlugZap, ShieldCheck, Table2 } from "lucide-react";
import { WorkspaceFrame } from "../_components/workspace-frame";
import { builtInSkills, sheetStoreKey } from "../_components/workspace-state";

const services=[{id:"sheets",name:"Google Sheets",description:"Read shipment, vendor and delivery records",icon:Table2},{id:"docs",name:"Google Docs",description:"Read operations documents",icon:FileStack},{id:"drive",name:"Google Drive",description:"Open selected operational files",icon:HardDrive},{id:"gmail",name:"Gmail",description:"Draft and send vendor email",icon:Mail},{id:"calendar",name:"Google Calendar",description:"Schedule vendor follow-ups",icon:Calendar}];
export default function ToolsPage(){
 const [connected,setConnected]=useState(false);const [granted,setGranted]=useState<string[]>([]);const [selected,setSelected]=useState<string[]>(["sheets"]);const [sheetId,setSheetId]=useState("");const [notice,setNotice]=useState("");
 useEffect(()=>{setSheetId(localStorage.getItem(sheetStoreKey)||"");fetch("/api/google/status").then(r=>r.json()).then(data=>{setConnected(Boolean(data.connected));setGranted(data.services||[]);if(data.services?.length)setSelected(data.services)}).catch(()=>{});const query=new URLSearchParams(location.search);if(query.has("google_error")){setNotice(query.get("google_error")==="missing_config"?"Add Google OAuth and Picker settings to .env.local, then restart the app.":"Google connection did not finish. Check the OAuth client setup and try again.");history.replaceState({},"",location.pathname)}},[]);
 function saveSheet(id:string){setSheetId(id);localStorage.setItem(sheetStoreKey,id)}
 async function chooseSheet(){try{if(!process.env.NEXT_PUBLIC_GOOGLE_API_KEY||!process.env.NEXT_PUBLIC_GOOGLE_PROJECT_NUMBER)throw new Error("Add the Google Picker API key and project number to .env.local.");const tokenResponse=await fetch("/api/google/picker-token");const token=await tokenResponse.json();if(!tokenResponse.ok)throw new Error(token.error);const pickerWindow=window as unknown as {gapi?:{load:(name:string,callback:()=>void)=>void};google?:any};if(!pickerWindow.gapi)await new Promise<void>((resolve,reject)=>{const script=document.createElement("script");script.src="https://apis.google.com/js/api.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("Could not load Google Picker."));document.head.appendChild(script)});pickerWindow.gapi!.load("picker",()=>{const picker=pickerWindow.google!.picker;const view=new picker.DocsView(picker.ViewId.SPREADSHEETS).setMimeTypes("application/vnd.google-apps.spreadsheet");new picker.PickerBuilder().addView(view).setOAuthToken(token.accessToken).setDeveloperKey(process.env.NEXT_PUBLIC_GOOGLE_API_KEY).setAppId(process.env.NEXT_PUBLIC_GOOGLE_PROJECT_NUMBER).setCallback((data:{action:string;docs?:Array<{id:string}>})=>{if(data.action===picker.Action.PICKED&&data.docs?.[0]?.id)saveSheet(data.docs[0].id)}).build().setVisible(true)})}catch(error){setNotice(error instanceof Error?error.message:"Could not open Google Picker.")}}
 async function disconnect(){await fetch("/api/google/status",{method:"DELETE"});setConnected(false);setGranted([]);setSelected(["sheets"])}
 return <WorkspaceFrame title="Tools" subtitle="Connect providers and keep permissions limited to the services your agents use."><div className="route-grid"><section className="route-panel"><div className="route-panel-heading"><div><span className="section-label">PROVIDER</span><h2><span className="google-mark">G</span> Google</h2></div><span className={`status-pill ${connected?"green":"amber"}`}>{connected?"CONNECTED":"NOT CONNECTED"}</span></div><p className="route-copy">Select services before connecting. Google asks you to approve only the selected access scopes.</p>{services.map(service=>{const Icon=service.icon;return <label className="service-row" key={service.id}><span className="service-icon"><Icon size={16}/></span><span><b>{service.name}</b><small>{service.description}{granted.includes(service.id)?" · access granted":""}</small></span><input type="checkbox" checked={selected.includes(service.id)} onChange={e=>setSelected(e.target.checked?[...selected,service.id]:selected.filter(x=>x!==service.id))}/></label>})}<div className="provider-actions"><a className="button primary" href={`/api/google/connect?services=${selected.join(",")}`}>{connected?"Update Google access":"Connect selected services"}</a>{connected&&<button className="button secondary" onClick={disconnect}>Disconnect</button>}</div>{notice&&<p className="route-error">{notice}</p>}<div className="route-note"><ShieldCheck size={15}/> Google Sheets uses per-file access. Select the spreadsheet below to authorize it.</div></section><section className="route-panel"><div className="route-panel-heading"><div><span className="section-label">DATA SOURCE</span><h2>Shipment spreadsheet</h2></div></div><p className="route-copy">Choose one spreadsheet. Agents assigned a Sheets capability read up to 500 rows from its first tab when they run a task.</p><label className="field-label">Selected file<input readOnly value={sheetId} placeholder="No spreadsheet selected"/></label><button className="button secondary" onClick={chooseSheet} disabled={!connected||!granted.includes("sheets")}>Choose Google Sheet</button><div className="route-note">The first row must contain column headers. The chosen file ID stays in this browser; the Google token stays in an HTTP-only cookie.</div></section><section className="route-panel"><div className="route-panel-heading"><div><span className="section-label">FRICTIONOS SKILLS</span><h2>Built-in tools</h2></div></div>{builtInSkills.map(skill=><div className="skill-row" key={skill}><span><Check size={13}/></span><div><b>{skill}</b><small>Available to every agent and included in the task audit trail.</small></div></div>)}</section></div></WorkspaceFrame>;
}
